### ISSUE TITLE
Support for other LaTeX compilers

### ISSUE THREAD

**Issue by johannesjmeyer** [cgogolin/quantum-journal#58]
Currently, the template is not working with LuaLaTeX or XeTeX. Minimal (not) working example is the quantum-template.tex. The issue seems to be related to the \pdfoutput command required for proper compilation on the arxiv.

**Comment by dbranford** [comment]
Having `\pdfoutput=1` in the template is probably a good idea as the arXiv is the principal destination for articles. I'd suggest issuing an error (overrideable by `nopdfoutputerror`) along the lines of https://github.com/quantum-journal/quantum-journal/blob/b6f451d670146cb188bd9909fefedeb7ca0ed8c1/quantumarticle.cls#L1245 at `\documentclass` (so as to avoid halting on the unclear error from `\pdfoutput=1`) if a different compiler is being used is the most desirable fix.  This would however break any file using the class and compiled with other compilers.

**Comment by johannesjmeyer** [comment]
I totally agree that `\pdfoutput=1` should be the default as the main objective of the template is submission to the arxiv. 

But as we also encourage the use of the template for other purposes we should not force people to use pdfLaTeX in those cases. An option `nopdfoutputerror` would surely be a salomonic solution for this.

There are several rather arxiv-specific regulations in the template already (for example the newly integrated `allowtoday` option). Maybe it would be good to include a new option `noarxiv` that sets `unpublished`, `allowtoday` and `nopdfoutputerror`.

**Comment by johannesjmeyer** [comment]
I just pushed a commit that just surrounded the calls to \pdfoutput with \ifcsdef{pdfoutput}. Now everything compiles in a charming way under Lua/XeLaTeX. Right now, if people don't use PdfLaTeX then there is no error if they don't put \pdfoutput=1. 

One could now think of producing an error if this is the case, along the lines of "You can not submit to the arxiv if you don't compile with PdfLaTeX" which is again remedied with a corresponding option. But this option hacking can't be the solution to everything.

**Comment by cgogolin** [comment]
I have been thinking back and forth about this for some time now and think it is fine to only show the error when pdflatex is used. If people decide to use a different compiled than the arxiv during writing, they should not be surprised if things break in unexpected ways when they upload.

My only concern is: What about people wo use plain latex during writing? They will never see the error, upload to the arxiv, then (I think) the arXiv will also use plain latex, and then the arXiv will not produce pdf output and we will get the problems with hyperlinks of dois that have been broken over several lines not working...

**Comment by cgogolin** [comment]
I think I much prefer to suppress the error about \pdfoutput=1 missing only if `noarxiv` is set.

**Comment by johannesjmeyer** [comment]
Ok, just to sum this up: The behaviour should be that

if `nopdfoutputerror` (which comes with `noarxiv`) is set: we don't care about `\pdfoutput=1`
else: throw an error no matter which compiler is used if `\pdfoutput=1` isn't set

This should be a quick fix, one only has to throw an error in the else part of `ifcsdef`.

Maybe we should think about having only the option `noarxiv` and not the finer grained ones that are set by it available to the user.

**Comment by cgogolin** [comment]
Yes, exactly.

Maybe we cab only describe the noarxiv option in the template and still have the other options as "hidden" features that reveal themselves via the corresponding error messages. Would that make sense?

**Comment by johannesjmeyer** [comment]
That is surely possible and not costly to implement. But after giving it some thought I'd prefer not to: I don't see a case where this will really be used -- most of these 'option hacks' are there to remedy some error we created to discipline the author so she/he submits nice documents to the arxiv. 

So either the author wants to submit to the arxiv and you need all those error messages or he doesn't and you don't need any of them, isn't it like this?

**Comment by cgogolin** [comment]
Ok, I see your argument. Still, we would still need to have all the individual error messages to tell the authors how to behave, the only thing it would save us is having all the individual toggles, but these should probably be keept just for backward compatibility. My preferred option is really to keep them all but prominently only explain the `noarxiv` option in the template. Ideally, it would be good to mention the noarxiv option as an alternative in all the error messages.

**Comment by johannesjmeyer** [comment]
This should be easily done after the refactoring is merged. I think going for the removing of the 'advertisements' of the other toggles and introducing the new noarxiv option is enough then.
